### 객실조회
GET http://localhost:8080//v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjk5OTksImlzcyI6Im5obi1hY2FkZW15LW1hcmNvIiwiaWF0IjoxNjg5MzI1Njk4LCJleHAiOjE2ODk0MTIwOTh9.YWYcb2knEv03rQ82aIgggqNZ5Yn71O8gCYrDmStgT7Y
Content-Type: application/json


### 객실생성
POST http://localhost:8080//v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjk5OTksImlzcyI6Im5obi1hY2FkZW15LW1hcmNvIiwiaWF0IjoxNjg5MzI1Njk4LCJleHAiOjE2ODk0MTIwOTh9.YWYcb2knEv03rQ82aIgggqNZ5Yn71O8gCYrDmStgT7Y
Content-Type: application/json

{
  "name" : "...",
  "capacity" : 2,
  "floor" : 3,
  "hasBathtub" : true,
  "viewType" : "oceanView"
}
