### 객실조회
GET http://localhost:8080//v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

### 객실생성
POST http://localhost:8080//v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

{
  "name": "...1",
  "capacity": 2,
  "floor": 3,
  "hasBathtub": true,
  "viewType": "oceanView"
}

### 에러 상황
POST /v1/hotel-api/hotels/100/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

{
  "name": "unique",
  "capacity": 200000000000,
  "floor": 3,
  "hasBathtub": true,
  "viewType": "cityView"
}

### 에러 메세지 통일
### 객실조회
GET http://localhost:8080//v1/hotel-api/hotels/105/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEwMCwiaXNzIjoibmhuLWFjYWRlbXktbWFyY28iLCJpYXQiOjE3MTA1MTIyMDgsImV4cCI6MTc5NjkxMjIwOH0.-sx5W47k7xEI24iTPSSFUzxOH8LNLzboDjmJlqykPkE
Content-Type: application/json

